Add reducer action
SimonGideon/BookstoreApp pull request #3
Opened 2022-12-19 22:38 UTC by SimonGideon

- Define action types for adding and removing a book.
- Set the initial state to be an empty array of books.
- Export Action Creators for your actions.

2022-12-19 23:14 UTC, emmiiorji requested changes
Hi @SimonGideon, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![A little bit more](https://user-images.githubusercontent.com/20554583/208546203-6d94fa76-7ada-4496-8c2c-27f01bb80ba1.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to use of GitHub flow
- Reducers and Actions are properly set up


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-19 23:14 UTC, emmiiorji commented on src/redux/categories/categories.js
> +const CHECK_STATUS = 'Bookstore/categories/UNDER_CONSTRUCTION';
In order to completely follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux) as stated in the [requirements](https://github.com/microverseinc/curriculum-react-redux/blob/5801583dd2ad132a9326d4bd429291d954e4e824/bookstore/add_reducers_an_actions.md?plain=1#L42), kindly modify the action types to have the form `npm-module-or-app/reducer/ACTION_TYPE`.

2022-12-19 23:14 UTC, emmiiorji commented on src/redux/books/books.js
> +const REMOVE_BOOK = 'Bookstore/books/REMOVE_BOOK';
Just as pointed out above, in order to completely follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux) as stated in the [requirements](https://github.com/microverseinc/curriculum-react-redux/blob/5801583dd2ad132a9326d4bd429291d954e4e824/bookstore/add_reducers_an_actions.md?plain=1#L42), kindly modify the action types to have the form npm-module-or-app/reducer/ACTION_TYPE.

2022-12-20 16:46 UTC, SimonGideon commented on src/redux/categories/categories.js
> +const CHECK_STATUS = 'Bookstore/categories/UNDER_CONSTRUCTION';
@emmiiorji Thanks for the review. Tha requested changes are corrected

2022-12-20 18:13 UTC, Gambit142 approved these changes
Hi @SimonGideon 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- All linters checks passed ✔️ 
- Good use of _**duck**_ pattern

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 18:14 UTC, merged